version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: supercat
      POSTGRES_PASSWORD: ${DB_PASS}
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:9200/_cat/health"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - 9200:9200
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - "elasticsearch"
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.1
    depends_on:
      - "elasticsearch"
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./logs/:/logs/
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    depends_on:
      - "elasticsearch"
    healthcheck:
      test: ["CMD", "curl", "-s", "-f", "http://localhost:5601/api/status"]
      interval: 3s
      timeout: 3s
      retries: 50
    ports:
      - 5601:5601