// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"playground.io/another-pet-store/controller"
	"playground.io/another-pet-store/db"
	"playground.io/another-pet-store/service"
)

// Injectors from controller_injector.go:

func NewAnimalController() controller.AnimalController {
	profileRepository := db.NewProfileRepository()
	profileService := service.NewProfileService(profileRepository)
	animalRepository := db.NewAnimalRepository()
	animalService := service.NewAnimalService(profileService, animalRepository)
	animalController := controller.NewAnimalController(animalService)
	return animalController
}

func NewLoginController() controller.LoginController {
	userService := service.NewUserService()
	profileRepository := db.NewProfileRepository()
	profileService := service.NewProfileService(profileRepository)
	jwtService := service.NewJWTService()
	loginService := service.NewLoginService(userService, profileService, jwtService)
	loginController := controller.NewLoginController(loginService)
	return loginController
}

func NewProfileController() controller.ProfileController {
	profileRepository := db.NewProfileRepository()
	profileService := service.NewProfileService(profileRepository)
	profileController := controller.NewProfileController(profileService)
	return profileController
}

func NewReferenceController() controller.ReferenceController {
	referenceRepository := db.NewReferenceRepository()
	referenceService := service.NewReferenceService(referenceRepository)
	referenceController := controller.NewReferenceController(referenceService)
	return referenceController
}

func NewSpecialOfferController() controller.SpecialOfferController {
	specialOfferRepository := db.NewSpecialOfferRepository()
	specialOfferService := service.NewSpecialOfferServie(specialOfferRepository)
	specialOfferController := controller.NewSpecialOfferController(specialOfferService)
	return specialOfferController
}

func NewChatController() controller.ChatController {
	chatRepository := db.NewChatRepository()
	chatService := service.NewChatService(chatRepository)
	chatController := controller.NewChatController(chatService)
	return chatController
}
