// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"playground.io/another-pet-store/controller"
	"playground.io/another-pet-store/db"
	"playground.io/another-pet-store/service"
)

// Injectors from controller_injector.go:

func NewAnimalController() controller.AnimalController {
	userService := service.NewUserService()
	jwtService := service.NewJWTService()
	profileRepository := db.NewProfileRepository()
	profileService := service.NewProfileService(userService, jwtService, profileRepository)
	animalRepository := db.NewAnimalRepository()
	animalService := service.NewAnimalService(profileService, animalRepository)
	animalController := controller.NewAnimalController(animalService)
	return animalController
}

func NewLoginController() controller.LoginController {
	userService := service.NewUserService()
	loginService := service.NewLoginService(userService)
	jwtService := service.NewJWTService()
	loginController := controller.NewLoginController(loginService, jwtService)
	return loginController
}

func NewProfileController() controller.ProfileController {
	userService := service.NewUserService()
	jwtService := service.NewJWTService()
	profileRepository := db.NewProfileRepository()
	profileService := service.NewProfileService(userService, jwtService, profileRepository)
	profileController := controller.NewProfileController(profileService)
	return profileController
}
